version: '3.4'

services:
  invoicemanagement:
    image: ${DOCKER_REGISTRY-}invoicemanagement
    build:
      context: .
      dockerfile: InvoiceManagement\Dockerfile
    ports:
      - "8080:80"  # Maps host port 8080 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # Example environment variable
    restart: always  # 